[book]
title = "The Linux Encyclopedia"
authors = ["Community"]
description = "A comprehensive, continuously growing reference for Linux, Unix internals, kernel development, system programming, administration, networking, security, and beyond."
language = "en"
src = "src"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Abhinav-Kumar012/lb2"
additional-css = ["custom.css"]
additional-js = ["custom.js", "mermaid-init.js", "mermaid.min.js"]
